#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

SIGTERM_hand()
{
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit 0
}


SIGQUIT_hand()
{
    rm /var/run/myscript.pid
    exit 0
}


SIGINT_hand()
{
    echo "Y U no love me?!"
}

trap "SIGTERM_hand" SIGTERM
trap "SIGINT_hand" SIGINT
trap "SIGQUIT_hand" SIGQUIT

PID=$(pgrep -f "100-process_and_pid_file")
echo "$PID" > /var/run/myscript.pid

while $1
do
echo "To infinity and beyond";
sleep 2
done
