#!/usr/bin/env bash
# This script displaysBest School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

a=1

while [ $a -le 10 ]
do
	echo "Best School"
	if [ $a -eq 9 ]; then
		echo "Hi"
	fi
	((a++))
done
