#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

a=0

while [ $a -lt 10 ]
do
	((a++))
	if [ $a -eq 4 ]; then
		echo "bad luck"
	elif [ $a -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
done
