#!/usr/bin/env bash
# displays information about file school

file="./school"

if [ -e $file ]; then
	echo "school file exist"
	if [ -s $file ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $file ]; then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi
